name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: '34'
          build-tools: '34.0.0'
      - name: Build release APK
        run: ./gradlew assembleRelease
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/outputs/apk/release/app-release.apk
          tag: ${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          token: ${{ secrets.GITHUB_TOKEN }}
